### ISSUE TITLE
endl, resetMatrix, oldMatrix are not defined

### ISSUE THREAD

**Issue by iamalminko** [akelmas/kn_plc#1]
C:\Users\User\Documents\spiele\kn_plc-main>mingw32-make
mingw32-make -f Makefile.Release
mingw32-make[1]: Entering directory 'C:/Users/User/Documents/spiele/kn_plc-main'
g++ -c -fno-keep-inline-dllexport -O2 -std=gnu++1z -Wall -Wextra -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I. -IC:/Qt/6.3.0/mingw_64/include -IC:/Qt/6.3.0/mingw_64/include/QtWidgets -IC:/Qt/6.3.0/mingw_64/include/QtGui -IC:/Qt/6.3.0/mingw_64/include/QtSerialPort -IC:/Qt/6.3.0/mingw_64/include/QtCore -Irelease -I/include -IC:/Qt/6.3.0/mingw_64/mkspecs/win32-g++  -o release\mainwindow.o mainwindow.cpp
mainwindow.cpp: In member function 'void MainWindow::fw_groupClicked(int)':
mainwindow.cpp:300:30: error: 'endl' was not declared in this scope
  300 |         qInfo()<<"settings"<<endl;
      |                              ^~~~
mainwindow.cpp:300:30: note: suggested alternatives:
In file included from c:\mingw\include\c++\11.2.0\istream:39,
                 from c:\mingw\include\c++\11.2.0\sstream:38,
                 from c:\mingw\include\c++\11.2.0\bits\quoted_string.h:38,
                 from c:\mingw\include\c++\11.2.0\iomanip:45,
                 from c:\mingw\include\c++\11.2.0\bits\fs_path.h:39,
                 from c:\mingw\include\c++\11.2.0\filesystem:45,
                 from C:/Qt/6.3.0/mingw_64/include/QtCore/qfile.h:49,
                 from C:/Qt/6.3.0/mingw_64/include/QtCore/qdir.h:44,
                 from C:/Qt/6.3.0/mingw_64/include/QtCore/QtCore:75,
                 from C:/Qt/6.3.0/mingw_64/include/QtWidgets/QtWidgetsDepends:3,
                 from C:/Qt/6.3.0/mingw_64/include/QtWidgets/QtWidgets:3,
                 from mainwindow.cpp:58:
c:\mingw\include\c++\11.2.0\ostream:681:5: note:   'std::endl'
  681 |     endl(basic_ostream<_CharT, _Traits>& __os)
      |     ^~~~
In file included from C:/Qt/6.3.0/mingw_64/include/QtCore/qdebug.h:48,
                 from C:/Qt/6.3.0/mingw_64/include/QtCore/qvariant.h:53,
                 from C:/Qt/6.3.0/mingw_64/include/QtWidgets/qgraphicsitem.h:45,
                 from C:/Qt/6.3.0/mingw_64/include/QtWidgets/QGraphicsLineItem:1,
                 from arrow.h:54,
                 from mainwindow.cpp:51:
C:/Qt/6.3.0/mingw_64/include/QtCore/qtextstream.h:256:28: note:   'Qt::endl'
  256 | Q_CORE_EXPORT QTextStream &endl(QTextStream &s);
      |                            ^~~~
mainwindow.cpp: In member function 'void MainWindow::sceneScaleChanged(const QString&)':
mainwindow.cpp:353:5: error: 'QMatrix' was not declared in this scope
  353 |     QMatrix oldMatrix = view->matrix();
      |     ^~~~~~~
mainwindow.cpp:354:11: error: 'class QGraphicsView' has no member named 'resetMatrix'
  354 |     view->resetMatrix();
      |           ^~~~~~~~~~~
mainwindow.cpp:355:21: error: 'oldMatrix' was not declared in this scope; did you mean 'glPopMatrix'?
  355 |     view->translate(oldMatrix.dx(), oldMatrix.dy());
      |                     ^~~~~~~~~
      |                     glPopMatrix
In file included from arrow.h:56,
                 from mainwindow.cpp:51:
diagramitem.h: At global scope:
diagramitem.h:73:13: warning: 'isMoveDone' defined but not used [-Wunused-variable]
   73 | static bool isMoveDone=true;
      |             ^~~~~~~~~~
mingw32-make[1]: *** [Makefile.Release:1283: release/mainwindow.o] Error 1
mingw32-make[1]: Leaving directory 'C:/Users/User/Documents/spiele/kn_plc-main'
mingw32-make: *** [Makefile:45: release] Error 2

**Comment by akelmas** [comment]
In Qt 6, some parts have become obsolete and/or refactored. That is why you are getting this error. It should compile with Qt 5.x.x. 
Basically, 
```diff
-    QMatrix oldMatrix = view->matrix();
-    view->resetMatrix();
+    QTransform oldMatrix = view->transform();
+    view->resetTransform();
```
should do the work, when trying to build with Qt 6.
